/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StkBnbStrategyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assessDepositFee"
      | "balanceOf"
      | "balanceOfPool"
      | "balanceOfToken"
      | "balanceOfWant"
      | "calculateYield"
      | "canDeposit"
      | "changeAddressStore"
      | "claim"
      | "claimAll"
      | "claimAndDistribute"
      | "deposit"
      | "depositAll"
      | "depositPaused"
      | "destination"
      | "distribute"
      | "distributeManual"
      | "endIndex"
      | "estimateInToken"
      | "harvest"
      | "initialize"
      | "manualWithdrawAmount"
      | "owner"
      | "panic"
      | "pause"
      | "renounceOwnership"
      | "rewards"
      | "setInterfaceImplementer"
      | "setRewards"
      | "setStrategist"
      | "startIndex"
      | "strategist"
      | "tokensReceived"
      | "transferOwnership"
      | "unpause"
      | "vault"
      | "withdraw"
      | "withdrawInToken"
      | "withdrawReqs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressStoreChanged"
      | "DepositPaused"
      | "DepositUnpaused"
      | "Harvested"
      | "Initialized"
      | "OwnershipTransferred"
      | "TokenReceived"
      | "UpdatedRewards"
      | "UpdatedStrategist"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assessDepositFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOfPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfWant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAddressStore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "claimAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimAndDistribute",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "destination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeManual",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "endIndex", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateInToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualWithdrawAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "panic", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rewards", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInterfaceImplementer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensReceived",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawInToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawReqs",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "assessDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfWant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeAddressStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAndDistribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeManual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateInToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualWithdrawAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "panic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInterfaceImplementer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStrategist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "strategist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawInToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawReqs",
    data: BytesLike
  ): Result;
}

export namespace AddressStoreChangedEvent {
  export type InputTuple = [addressStore: AddressLike];
  export type OutputTuple = [addressStore: string];
  export interface OutputObject {
    addressStore: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositPausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositUnpausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenReceivedEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    data: BytesLike,
    operatorData: BytesLike
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    amount: bigint,
    data: string,
    operatorData: string
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    amount: bigint;
    data: string;
    operatorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedRewardsEvent {
  export type InputTuple = [rewards: AddressLike];
  export type OutputTuple = [rewards: string];
  export interface OutputObject {
    rewards: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedStrategistEvent {
  export type InputTuple = [strategist: AddressLike];
  export type OutputTuple = [strategist: string];
  export interface OutputObject {
    strategist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StkBnbStrategy extends BaseContract {
  connect(runner?: ContractRunner | null): StkBnbStrategy;
  waitForDeployment(): Promise<this>;

  interface: StkBnbStrategyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assessDepositFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOf: TypedContractMethod<[], [bigint], "view">;

  balanceOfPool: TypedContractMethod<[], [bigint], "view">;

  balanceOfToken: TypedContractMethod<[], [bigint], "view">;

  balanceOfWant: TypedContractMethod<[], [bigint], "view">;

  calculateYield: TypedContractMethod<[], [bigint], "view">;

  canDeposit: TypedContractMethod<[amount: BigNumberish], [boolean], "view">;

  changeAddressStore: TypedContractMethod<
    [addressStore: AddressLike],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  claimAll: TypedContractMethod<[], [void], "nonpayable">;

  claimAndDistribute: TypedContractMethod<[], [void], "nonpayable">;

  deposit: TypedContractMethod<[], [bigint], "payable">;

  depositAll: TypedContractMethod<[], [void], "nonpayable">;

  depositPaused: TypedContractMethod<[], [boolean], "view">;

  destination: TypedContractMethod<[], [string], "view">;

  distribute: TypedContractMethod<[endIdx: BigNumberish], [void], "nonpayable">;

  distributeManual: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  endIndex: TypedContractMethod<[], [bigint], "view">;

  estimateInToken: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  harvest: TypedContractMethod<[], [void], "nonpayable">;

  initialize: TypedContractMethod<
    [
      destination: AddressLike,
      rewards: AddressLike,
      masterVault: AddressLike,
      addressStore: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  manualWithdrawAmount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  panic: TypedContractMethod<[], [bigint], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewards: TypedContractMethod<[], [string], "view">;

  setInterfaceImplementer: TypedContractMethod<[], [void], "nonpayable">;

  setRewards: TypedContractMethod<
    [newRewardsAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  setStrategist: TypedContractMethod<
    [newStrategist: AddressLike],
    [void],
    "nonpayable"
  >;

  startIndex: TypedContractMethod<[], [bigint], "view">;

  strategist: TypedContractMethod<[], [string], "view">;

  tokensReceived: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vault: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  withdrawInToken: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  withdrawReqs: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { recipient: string; amount: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assessDepositFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfWant"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canDeposit"
  ): TypedContractMethod<[amount: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "changeAddressStore"
  ): TypedContractMethod<[addressStore: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimAndDistribute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "depositAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "destination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<[endIdx: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeManual"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "estimateInToken"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvest"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      destination: AddressLike,
      rewards: AddressLike,
      masterVault: AddressLike,
      addressStore: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manualWithdrawAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "panic"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setInterfaceImplementer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewards"
  ): TypedContractMethod<[newRewardsAddr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategist"
  ): TypedContractMethod<[newStrategist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "strategist"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokensReceived"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawInToken"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawReqs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { recipient: string; amount: bigint }],
    "view"
  >;

  getEvent(
    key: "AddressStoreChanged"
  ): TypedContractEvent<
    AddressStoreChangedEvent.InputTuple,
    AddressStoreChangedEvent.OutputTuple,
    AddressStoreChangedEvent.OutputObject
  >;
  getEvent(
    key: "DepositPaused"
  ): TypedContractEvent<
    DepositPausedEvent.InputTuple,
    DepositPausedEvent.OutputTuple,
    DepositPausedEvent.OutputObject
  >;
  getEvent(
    key: "DepositUnpaused"
  ): TypedContractEvent<
    DepositUnpausedEvent.InputTuple,
    DepositUnpausedEvent.OutputTuple,
    DepositUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenReceived"
  ): TypedContractEvent<
    TokenReceivedEvent.InputTuple,
    TokenReceivedEvent.OutputTuple,
    TokenReceivedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedRewards"
  ): TypedContractEvent<
    UpdatedRewardsEvent.InputTuple,
    UpdatedRewardsEvent.OutputTuple,
    UpdatedRewardsEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedStrategist"
  ): TypedContractEvent<
    UpdatedStrategistEvent.InputTuple,
    UpdatedStrategistEvent.OutputTuple,
    UpdatedStrategistEvent.OutputObject
  >;

  filters: {
    "AddressStoreChanged(address)": TypedContractEvent<
      AddressStoreChangedEvent.InputTuple,
      AddressStoreChangedEvent.OutputTuple,
      AddressStoreChangedEvent.OutputObject
    >;
    AddressStoreChanged: TypedContractEvent<
      AddressStoreChangedEvent.InputTuple,
      AddressStoreChangedEvent.OutputTuple,
      AddressStoreChangedEvent.OutputObject
    >;

    "DepositPaused()": TypedContractEvent<
      DepositPausedEvent.InputTuple,
      DepositPausedEvent.OutputTuple,
      DepositPausedEvent.OutputObject
    >;
    DepositPaused: TypedContractEvent<
      DepositPausedEvent.InputTuple,
      DepositPausedEvent.OutputTuple,
      DepositPausedEvent.OutputObject
    >;

    "DepositUnpaused()": TypedContractEvent<
      DepositUnpausedEvent.InputTuple,
      DepositUnpausedEvent.OutputTuple,
      DepositUnpausedEvent.OutputObject
    >;
    DepositUnpaused: TypedContractEvent<
      DepositUnpausedEvent.InputTuple,
      DepositUnpausedEvent.OutputTuple,
      DepositUnpausedEvent.OutputObject
    >;

    "Harvested(address,uint256)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenReceived(address,address,address,uint256,bytes,bytes)": TypedContractEvent<
      TokenReceivedEvent.InputTuple,
      TokenReceivedEvent.OutputTuple,
      TokenReceivedEvent.OutputObject
    >;
    TokenReceived: TypedContractEvent<
      TokenReceivedEvent.InputTuple,
      TokenReceivedEvent.OutputTuple,
      TokenReceivedEvent.OutputObject
    >;

    "UpdatedRewards(address)": TypedContractEvent<
      UpdatedRewardsEvent.InputTuple,
      UpdatedRewardsEvent.OutputTuple,
      UpdatedRewardsEvent.OutputObject
    >;
    UpdatedRewards: TypedContractEvent<
      UpdatedRewardsEvent.InputTuple,
      UpdatedRewardsEvent.OutputTuple,
      UpdatedRewardsEvent.OutputObject
    >;

    "UpdatedStrategist(address)": TypedContractEvent<
      UpdatedStrategistEvent.InputTuple,
      UpdatedStrategistEvent.OutputTuple,
      UpdatedStrategistEvent.OutputObject
    >;
    UpdatedStrategist: TypedContractEvent<
      UpdatedStrategistEvent.InputTuple,
      UpdatedStrategistEvent.OutputTuple,
      UpdatedStrategistEvent.OutputObject
    >;
  };
}
