/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAddressStore,
  IAddressStoreInterface,
} from "../../../../contracts/stkBNB/interfaces/IAddressStore";

const _abi = [
  {
    inputs: [],
    name: "getStakePool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStkBNB",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAddressStore__factory {
  static readonly abi = _abi;
  static createInterface(): IAddressStoreInterface {
    return new Interface(_abi) as IAddressStoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAddressStore {
    return new Contract(address, _abi, runner) as unknown as IAddressStore;
  }
}
