/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  DaiJoinLike,
  DaiJoinLikeInterface,
} from "../../../../contracts/mock/proxyLike.sol/DaiJoinLike";

const _abi = [
  {
    inputs: [],
    name: "dai",
    outputs: [
      {
        internalType: "contract GemLike",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class DaiJoinLike__factory {
  static readonly abi = _abi;
  static createInterface(): DaiJoinLikeInterface {
    return new Interface(_abi) as DaiJoinLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DaiJoinLike {
    return new Contract(address, _abi, runner) as unknown as DaiJoinLike;
  }
}
