/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClipperLike } from "./ClipperLike";
export type { DogLike } from "./DogLike";
export type { GemJoinLike } from "./GemJoinLike";
export type { GemLike } from "./GemLike";
export type { HayJoinLike } from "./HayJoinLike";
export type { HayLike } from "./HayLike";
export type { IAuctionProxy } from "./IAuctionProxy";
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
export type { IMovingWindowOracle } from "./IMovingWindowOracle";
export type { IRewards } from "./IRewards";
export type { JugLike } from "./JugLike";
export type { PipLike } from "./PipLike";
export type { SpotLike } from "./SpotLike";
export type { VatLike } from "./VatLike";
