/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBinancePool,
  IBinancePoolInterface,
} from "../../../../contracts/ceros/interfaces/IBinancePool";

const _abi = [
  {
    inputs: [],
    name: "getMinimumStake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRelayerFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "claimer",
        type: "address",
      },
    ],
    name: "pendingUnstakesOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stakeAndClaimCerts",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "unstakeCertsFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBinancePool__factory {
  static readonly abi = _abi;
  static createInterface(): IBinancePoolInterface {
    return new Interface(_abi) as IBinancePoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBinancePool {
    return new Contract(address, _abi, runner) as unknown as IBinancePool;
  }
}
