/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClipperLike } from "./ClipperLike";
export type { Dog } from "./Dog";
export type { VatLike } from "./VatLike";
