/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  HayJoinLike,
  HayJoinLikeInterface,
} from "../../../contracts/interfaces/HayJoinLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class HayJoinLike__factory {
  static readonly abi = _abi;
  static createInterface(): HayJoinLikeInterface {
    return new Interface(_abi) as HayJoinLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): HayJoinLike {
    return new Contract(address, _abi, runner) as unknown as HayJoinLike;
  }
}
