/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMovingWindowOracle,
  IMovingWindowOracleInterface,
} from "../../../contracts/interfaces/IMovingWindowOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
    ],
    name: "consult",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMovingWindowOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IMovingWindowOracleInterface {
    return new Interface(_abi) as IMovingWindowOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMovingWindowOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMovingWindowOracle;
  }
}
