/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Elipsis__factory } from "./Elipsis__factory";
export { ElipsisMediator__factory } from "./ElipsisMediator__factory";
