/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ClipperCallee,
  ClipperCalleeInterface,
} from "../../../contracts/clip.sol/ClipperCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "clipperCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ClipperCallee__factory {
  static readonly abi = _abi;
  static createInterface(): ClipperCalleeInterface {
    return new Interface(_abi) as ClipperCalleeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ClipperCallee {
    return new Contract(address, _abi, runner) as unknown as ClipperCallee;
  }
}
