/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SpotterLike,
  SpotterLikeInterface,
} from "../../../contracts/clip.sol/SpotterLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "ilks",
    outputs: [
      {
        internalType: "contract PipLike",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "par",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SpotterLike__factory {
  static readonly abi = _abi;
  static createInterface(): SpotterLikeInterface {
    return new Interface(_abi) as SpotterLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SpotterLike {
    return new Contract(address, _abi, runner) as unknown as SpotterLike;
  }
}
